# generated by datamodel-codegen:
#   filename:  profile_schema.json
#   timestamp: 2024-04-27T21:51:42+00:00

from __future__ import annotations

from enum import Enum
from typing import Any, List, Optional, Union

from pydantic import BaseModel


class Type(Enum):
    leak = 'leak'
    service = 'service'
    url = 'url'
    input = 'input'


class Source(BaseModel):
    name: Optional[str] = None
    id: Optional[str] = None
    chain: Optional[str] = None
    type: Optional[Type] = None
    infallibility: Optional[float] = None
    date: Optional[str] = None


class Name(BaseModel):
    full: Optional[str] = None
    first: Optional[str] = None
    last: Optional[str] = None
    middle: Optional[str] = None
    prefix: Optional[str] = None
    suffix: Optional[str] = None
    sources: List[Source]


class Source1(BaseModel):
    name: Optional[str] = None
    id: Optional[str] = None
    chain: Optional[str] = None
    type: Optional[Type] = None
    infallibility: Optional[float] = None
    date: Optional[str] = None


class Birthdate(BaseModel):
    raw: Optional[Union[str, float]] = None
    year: Optional[Union[int, str]] = None
    month: Optional[Union[int, str]] = None
    day: Optional[Union[int, str]] = None
    sources: List[Source1]


class Source2(BaseModel):
    name: Optional[str] = None
    id: Optional[str] = None
    chain: Optional[str] = None
    type: Optional[Type] = None
    infallibility: Optional[float] = None
    date: Optional[str] = None


class Gender(BaseModel):
    raw: Optional[Union[float, str, bool]] = None
    sources: List[Source2]


class Source3(BaseModel):
    name: Optional[str] = None
    id: Optional[str] = None
    chain: Optional[str] = None
    type: Optional[Type] = None
    date: Optional[str] = None


class Email(BaseModel):
    email: Optional[str] = None
    sources: List[Source3]


class Source4(BaseModel):
    name: Optional[str] = None
    id: Optional[str] = None
    chain: Optional[str] = None
    type: Optional[Type] = None
    date: Optional[str] = None


class Phone(BaseModel):
    phone: Optional[str] = None
    sources: List[Source4]


class Geo(BaseModel):
    latitude: Optional[float] = None
    longitude: Optional[float] = None


class Source5(BaseModel):
    name: Optional[str] = None
    id: Optional[str] = None
    chain: Optional[str] = None
    type: Optional[Type] = None
    date: Optional[str] = None


class Location(BaseModel):
    raw: Optional[str] = None
    country: Optional[Any] = None
    city: Optional[Any] = None
    state: Optional[Any] = None
    postcode: Optional[Union[int, str]] = None
    geo: Optional[Geo] = None
    address: Optional[str] = None
    url: Optional[str] = None
    types: Optional[List[str]] = None
    name: Optional[str] = None
    date: Optional[Any] = None
    sources: List[Source5]


class Source6(BaseModel):
    name: Optional[str] = None
    id: Optional[str] = None
    chain: Optional[str] = None
    type: Optional[Type] = None
    date: Optional[str] = None


class LocaleItem(BaseModel):
    country: Optional[str] = None
    language: Optional[str] = None
    sources: List[Source6]


class Source7(BaseModel):
    name: Optional[str] = None
    id: Optional[str] = None
    chain: Optional[str] = None
    type: Optional[Type] = None
    date: Optional[str] = None


class Photo(BaseModel):
    url: str
    sources: List[Source7]


class Start(BaseModel):
    raw: Optional[Union[str, float]] = None
    month: Optional[Union[int, str]] = None
    year: Optional[Union[int, str]] = None
    day: Optional[Union[int, str]] = None


class End(BaseModel):
    raw: Optional[Union[str, float]] = None
    month: Optional[Union[int, str]] = None
    year: Optional[Union[int, str]] = None
    day: Optional[Union[int, str]] = None


class Source8(BaseModel):
    name: Optional[str] = None
    id: Optional[str] = None
    chain: Optional[str] = None
    type: Optional[Type] = None
    date: Optional[str] = None


class Job(BaseModel):
    position: Optional[str] = None
    start: Optional[Start] = None
    end: Optional[End] = None
    description: Optional[str] = None
    company: Optional[str] = None
    location: Optional[str] = None
    logo: Optional[str] = None
    linkedin_url: Optional[str] = None
    sources: List[Source8]


class Start1(BaseModel):
    year: Optional[Union[int, str]] = None
    month: Optional[Union[int, str]] = None
    day: Optional[Union[int, str]] = None


class End1(BaseModel):
    year: Optional[Union[int, str]] = None
    month: Optional[Union[int, str]] = None
    day: Optional[Union[int, str]] = None


class Source9(BaseModel):
    name: Optional[str] = None
    id: Optional[str] = None
    chain: Optional[str] = None
    type: Optional[Type] = None
    date: Optional[str] = None


class EducationItem(BaseModel):
    name: Optional[str] = None
    location: Optional[str] = None
    logo: Optional[str] = None
    linkedin_url: Optional[str] = None
    degree: Optional[str] = None
    start: Optional[Start1] = None
    end: Optional[End1] = None
    field: Optional[str] = None
    sources: List[Source9]


class Source10(BaseModel):
    name: Optional[str] = None
    id: Optional[str] = None
    chain: Optional[str] = None
    type: Optional[Type] = None
    date: Optional[str] = None


class Interest(BaseModel):
    name: Optional[str] = None
    sources: List[Source10]


class Date(BaseModel):
    raw: Optional[Union[str, float]] = None
    month: Optional[int] = None
    year: Optional[int] = None
    day: Optional[int] = None


class Source11(BaseModel):
    name: Optional[str] = None
    id: Optional[str] = None
    chain: Optional[str] = None
    type: Optional[Type] = None
    date: Optional[str] = None


class Text(BaseModel):
    title: Optional[str] = None
    body: Optional[str] = None
    url: Optional[str] = None
    date: Optional[Date] = None
    type: Optional[str] = None
    sources: Optional[List[Source11]] = None


class Event(BaseModel):
    name: Optional[str] = None
    raw: Optional[Union[int, str]] = None
    year: Optional[Union[int, str]] = None
    month: Optional[Union[int, str]] = None
    day: Optional[Union[int, str]] = None


class Source12(BaseModel):
    name: Optional[str] = None
    id: Optional[str] = None
    chain: Optional[str] = None
    type: Optional[Type] = None
    infallibility: Optional[float] = None
    date: Optional[str] = None


class Source13(BaseModel):
    name: Optional[str] = None
    id: Optional[str] = None
    chain: Optional[str] = None
    type: Optional[Type] = None
    date: Optional[str] = None


class Alias(BaseModel):
    alias: Optional[str] = None
    sources: Optional[List[Source13]] = None


class Source14(BaseModel):
    name: Optional[str] = None
    id: Optional[str] = None
    chain: Optional[str] = None
    type: Optional[Type] = None
    date: Optional[str] = None


class Password(BaseModel):
    password: Optional[str] = None
    hash: Optional[str] = None
    sources: Optional[List[Source14]] = None


class Source15(BaseModel):
    name: Optional[str] = None
    id: Optional[str] = None
    chain: Optional[str] = None
    type: Optional[Type] = None
    date: Optional[str] = None


class IpItem(BaseModel):
    ip: Optional[Any] = None
    sources: Optional[List[Source15]] = None


class Source16(BaseModel):
    name: Optional[str] = None
    id: Optional[str] = None
    chain: Optional[str] = None
    type: Optional[Type] = None
    date: Optional[str] = None


class Id(BaseModel):
    id: Optional[str] = None
    service: Optional[str] = None
    sources: Optional[List[Source16]] = None


class Name1(BaseModel):
    full: Optional[str] = None
    first: Optional[str] = None
    last: Optional[str] = None


class Source17(BaseModel):
    name: Optional[str] = None
    id: Optional[str] = None
    chain: Optional[str] = None
    type: Optional[Type] = None
    date: Optional[str] = None


class SocialConnection(BaseModel):
    name: Optional[Name1] = None
    url: Optional[str] = None
    photo: Optional[str] = None
    types: Optional[List[str]] = None
    sources: Optional[List[Source17]] = None


class Model(BaseModel):
    names: Optional[List[Name]] = None
    birthdate: Optional[Birthdate] = None
    gender: Optional[Gender] = None
    emails: Optional[List[Email]] = None
    phones: Optional[List[Phone]] = None
    locations: Optional[List[Location]] = None
    locale: Optional[List[LocaleItem]] = None
    photos: Optional[List[Photo]] = None
    jobs: Optional[List[Job]] = None
    education: Optional[List[EducationItem]] = None
    interests: Optional[List[Interest]] = None
    texts: Optional[List[Text]] = None
    events: Optional[List[Event]] = None
    sources: List[Source12]
    aliases: Optional[List[Alias]] = None
    passwords: Optional[List[Password]] = None
    urls: Optional[List[str]] = None
    ip: Optional[List[IpItem]] = None
    ids: Optional[List[Id]] = None
    social_connections: Optional[List[SocialConnection]] = None
